### ISSUE TITLE
关于mysql

### ISSUE THREAD

**Issue by easliec** [HHXiaoFu/StudyListSSM.github.io#2]
请问是否有对应的sql文件呢

**Comment by HHXiaoFu** [comment]
> 请问是否有对应的sql文件呢

请问能否提供邮箱 地址 ，我会将 plansystem.sql 以附件的形式发送给您

**Comment by easliec** [comment]
> 
十分感谢你。mrwqiao@163.com

**Comment by Joewx21** [comment]
最近才看到邮件。感谢你。mrwqiao@163.com
